[project]
name = "agent-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "chromadb>=1.5.9",
    "ddgs>=9.14.4",
    "google-genai>=2.8.0",
    "langchain-core>=1.4.8",
    "langgraph>=1.2.7",
    "pandas>=2.3.3",
    "pydantic-settings>=2.14.1",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "scikit-learn>=1.7.2",
    "trafilatura>=2.1.0",
]


